package physics06;

import java.util.Arrays;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import static physics06.Physics06Settings.*;

/**
 *
 * @author Administrator
 */
public class Physics06OptionsDialog extends javax.swing.JDialog {


    /** Creates new form Physics06OptionsDialog */
    public Physics06OptionsDialog() {
        super(frame, true);
        initComponents();
        myInit();
        setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupParamType = new javax.swing.ButtonGroup();
        buttonGroupDt = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jRadioButtonSpring = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldM = new javax.swing.JTextField();
        jTextFieldK = new javax.swing.JTextField();
        jTextFieldB = new javax.swing.JTextField();
        jRadioButtonCommon = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldBeta = new javax.swing.JTextField();
        jTextFieldW0 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxSearchType = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldLeftW = new javax.swing.JTextField();
        jTextFieldRightW = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jRadioButtonRealDT = new javax.swing.JRadioButton();
        jRadioButtonCustomDT = new javax.swing.JRadioButton();
        jTextFieldCustomDT = new javax.swing.JTextField();
        jButtonOK = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldF = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldFileName = new javax.swing.JTextField();
        jButtonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Options");
        setBackground(new java.awt.Color(0, 0, 0));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Параметры");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Параметры системы");

        jRadioButtonSpring.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroupParamType.add(jRadioButtonSpring);
        jRadioButtonSpring.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonSpring.setSelected(true);
        jRadioButtonSpring.setText("Пружинный маятник");
        jRadioButtonSpring.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSpringActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Масса(m)");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Жесткость(k)");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Сопротивление(b)");

        jTextFieldM.setText("0");
        jTextFieldM.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jTextFieldK.setText("0");

        jTextFieldB.setText("0");

        jRadioButtonCommon.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroupParamType.add(jRadioButtonCommon);
        jRadioButtonCommon.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonCommon.setText("Общего вида");
        jRadioButtonCommon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCommonActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Сопротивление(β)");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Собст. част.(ω0)");

        jTextFieldBeta.setText("0");
        jTextFieldBeta.setEnabled(false);

        jTextFieldW0.setText("0");
        jTextFieldW0.setEnabled(false);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Параметры поиска");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Тип поиска");

        jComboBoxSearchType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Постепенный", "Тернарный" }));
        jComboBoxSearchType.setToolTipText("");
        jComboBoxSearchType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSearchTypeActionPerformed(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Границы для ω");

        jTextFieldLeftW.setText("0.1");

        jTextFieldRightW.setText("50");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("dt:");

        jRadioButtonRealDT.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroupDt.add(jRadioButtonRealDT);
        jRadioButtonRealDT.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonRealDT.setSelected(true);
        jRadioButtonRealDT.setText("Реальное время");
        jRadioButtonRealDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonRealDTActionPerformed(evt);
            }
        });

        jRadioButtonCustomDT.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroupDt.add(jRadioButtonCustomDT);
        jRadioButtonCustomDT.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonCustomDT.setText("Свое(мс)");
        jRadioButtonCustomDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCustomDTActionPerformed(evt);
            }
        });

        jTextFieldCustomDT.setText("10");
        jTextFieldCustomDT.setEnabled(false);

        jButtonOK.setText("OK");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Разное");

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("F=");

        jTextFieldF.setToolTipText("Переменные: t, w, pi.\nФункции: abs, cos, sin, tg, ctg, sign, exp, ln");

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Имя файла (без расширения)");

        jTextFieldFileName.setText("temp");
        jTextFieldFileName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jButtonCancel.setText("Отмена");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldF))
                            .addComponent(jRadioButtonSpring, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldW0))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldBeta))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldM))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldK))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldB, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jRadioButtonCommon, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jRadioButtonCustomDT)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBoxSearchType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextFieldLeftW, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldRightW))
                                    .addComponent(jLabel11)
                                    .addComponent(jRadioButtonRealDT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldCustomDT))
                                .addGap(18, 18, 18)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jTextFieldFileName, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)))
                            .addComponent(jButtonOK, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonSpring)
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonCommon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextFieldBeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextFieldW0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxSearchType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldLeftW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldRightW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonRealDT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonCustomDT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCustomDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addGap(4, 4, 4)
                        .addComponent(jTextFieldFileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonOK)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCancel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        try {
            renew();
        } catch (NumberFormatException exc) {
            JOptionPane.showMessageDialog(this, exc.getMessage());
            return;
        }
        frame.renew();
        this.dispose();
        frame.repaint();
    }//GEN-LAST:event_jButtonOKActionPerformed

    private void jRadioButtonSpringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSpringActionPerformed
        boolean b = jRadioButtonSpring.isSelected();
        jTextFieldM.setEnabled(b);
        jTextFieldK.setEnabled(b);
        jTextFieldB.setEnabled(b);
        jTextFieldBeta.setEnabled(!b);
        jTextFieldW0.setEnabled(!b);
    }//GEN-LAST:event_jRadioButtonSpringActionPerformed

    private void jRadioButtonCommonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCommonActionPerformed
        boolean b = jRadioButtonCommon.isSelected();
        jTextFieldM.setEnabled(!b);
        jTextFieldK.setEnabled(!b);
        jTextFieldB.setEnabled(!b);
        jTextFieldBeta.setEnabled(b);
        jTextFieldW0.setEnabled(b);
    }//GEN-LAST:event_jRadioButtonCommonActionPerformed

    private void jRadioButtonRealDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonRealDTActionPerformed
        boolean b = jRadioButtonRealDT.isSelected();
        jTextFieldCustomDT.setEnabled(!b);
    }//GEN-LAST:event_jRadioButtonRealDTActionPerformed

    private void jRadioButtonCustomDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCustomDTActionPerformed
        boolean b = jRadioButtonCustomDT.isSelected();
        jTextFieldCustomDT.setEnabled(b);
    }//GEN-LAST:event_jRadioButtonCustomDTActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        this.dispose();
        frame.repaint();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jComboBoxSearchTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSearchTypeActionPerformed
    }//GEN-LAST:event_jComboBoxSearchTypeActionPerformed

    private void myInit() {
        setLocation((Toolkit.getDefaultToolkit().getScreenSize().width - getWidth()) / 2,
                (Toolkit.getDefaultToolkit().getScreenSize().height - getHeight()) / 2);
        jTextFieldM.setText("" + m);
        jTextFieldK.setText("" + k);
        jTextFieldB.setText("" + b);
        jTextFieldBeta.setText("" + beta);
        jTextFieldW0.setText("" + w0);
        jTextFieldF.setText(F);
        if (searchType == SearchType.TERNARY) {
            jComboBoxSearchType.setSelectedIndex(1);
        } else {
            jComboBoxSearchType.setSelectedIndex(0);
        }
        jTextFieldLeftW.setText("" + leftW);
        jTextFieldRightW.setText("" + rightW);
        if (customDT == 0) {
            jRadioButtonRealDT.setSelected(true);
            jTextFieldCustomDT.setEnabled(false);
        } else {
            jRadioButtonCustomDT.setSelected(true);
            jTextFieldCustomDT.setEnabled(true);
        }
        jTextFieldCustomDT.setText("" + customDT);
//        jCheckBoxGraphShow.setSelected(showHOGraph);
    }

    private void renew() throws NumberFormatException {
        firstIteration = true;
        place = 0;
        V = 0;
        a = 0;
        time = 0;
        graphSpring.clear();
        graphRes.clear();
        minA = maxA = 0;
        periodCount = 0;
        graphRes.clear();
        Arrays.fill(wasFract, false);
        if (jRadioButtonSpring.isSelected()) {
            m = getFloat(jTextFieldM);
            k = getFloat(jTextFieldK);
            b = getFloat(jTextFieldB);
            beta = b / (2 * m);
            w0 = (float) Math.sqrt(k / m);
        } else {
            beta = getFloat(jTextFieldBeta);
            w0 = getFloat(jTextFieldW0);
            m = 1;
            k = w0 * w0;
            b = 2 * beta;
        }
        F = jTextFieldF.getText();
        chosenLeftW = leftW = getFloat(jTextFieldLeftW);
        chosenRightW = rightW = getFloat(jTextFieldRightW);
        resizeHistory.clear();
        graph1X0 = chosenLeftW;
        try {
            ex = new Expression(F);
        } catch (Exception exc) {
            log("Bad expression: " + F, exc);
        }
        if (jRadioButtonRealDT.isSelected()) {
            customDT = 0;
        } else {
            customDT = getFloat(jTextFieldCustomDT);
        }
//        showHOGraph = jCheckBoxGraphShow.isSelected();
        fileVersion = 2;
        fileName = "saves/" + jTextFieldFileName.getText() + ".ph06";
        if (jComboBoxSearchType.getSelectedIndex() == 0) {
            searchType = SearchType.DELTA;
            nextW_DeltaSearch();
        } else {
            searchType = SearchType.TERNARY;
            nextW_TernarySearch();
        }
        frame.setW(w);
        frame.setDone(periodCount);
        clear();
    }

    private float getFloat(JTextField field) throws NumberFormatException {
        String s = field.getText();
        if (s.length() == 0) {
            return 0;
        } else {
            return Float.parseFloat(s);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupDt;
    private javax.swing.ButtonGroup buttonGroupParamType;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JComboBox jComboBoxSearchType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonCommon;
    private javax.swing.JRadioButton jRadioButtonCustomDT;
    private javax.swing.JRadioButton jRadioButtonRealDT;
    private javax.swing.JRadioButton jRadioButtonSpring;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextFieldB;
    private javax.swing.JTextField jTextFieldBeta;
    private javax.swing.JTextField jTextFieldCustomDT;
    private javax.swing.JTextField jTextFieldF;
    private javax.swing.JTextField jTextFieldFileName;
    private javax.swing.JTextField jTextFieldK;
    private javax.swing.JTextField jTextFieldLeftW;
    private javax.swing.JTextField jTextFieldM;
    private javax.swing.JTextField jTextFieldRightW;
    private javax.swing.JTextField jTextFieldW0;
    // End of variables declaration//GEN-END:variables
}
